version: 1
# 定义日志输出格式,可以有多种格式输出
formatters:
  simple:
    format: "%(message)s"
  error:
    format: "%(asctime)s [%(name)s] [%(levelname)s]:%(levelno)s: %(message)s"

# 定义不同的handler,输出不同等级的日志消息
handlers:
  console:
    class: logging.StreamHandler # 输出到控制台
    level: DEBUG
    formatter: simple
    stream: ext://flask.logging.wsgi_errors_stream # 监听flask日志
  info_file_handler:
    class: logging.handlers.RotatingFileHandler # 输出到文件
