zh_CN:
  0: "成功"
  -1: "失败"
  999: "未知错误"
  40002: "参数无效"
  40003: "账户或密码错误"
en:
  # 英文编码
  0: "success"
  -1: "fail"
  999: "No resources found"
  40002: "Invalid argument"
  40003: "Incorrect account or password"

